Import comb from scipy.special instead of scipy.misc
`comb` has been moved from `scipy.misc` to `scipy.special`:

```
AttributeError: module 'scipy.misc' has no attribute 'comb'
```