Custom unpickler to handle renamed modules
We recently renamed a lot of our packages from ibeis to wbia.  This
caused errors during doctests like:

```
  File "/wbia/wbia-plugin-cnn/wbia_cnn/_plugin.py", line 876, in generate_species_background
    model_state = ut.load_cPkl(model_state_fpath)
  File "/wbia/utool/utool/util_io.py", line 342, in load_cPkl
    data = pickle.load(file_, encoding='latin1')
ModuleNotFoundError: No module named 'ibeis_cnn'
```

In order to fix this, I created a custom unpickler and overridden the
`find_class` method to replace the module names and function names from
ibeis to wbia.  This will probably need further adjustments as we go
through more examples of pickled files.